name: Loan
version: '${project.version}'
main: me.sirmonkeyboy.loan.Loan
api-version: '1.20'
depend: [Vault]
authors: [SirMonkeyBoy]
description: Loan Plugin for minecraft
website: https://github.com/SirMonkeyBoy
commands:
  Loan:
    description: Helpful server setup commands
    usage: /<command>